### ISSUE TITLE
Crash Houdini 18.5.563

### ISSUE THREAD

**Issue by MaxSteven** [eglaubauf/egRedshiftTools#1]
For some reason it made Houdini 18.5.563 crashed and can't start up!

**Comment by MaxSteven** [comment]
Well I think it's simply the tool does not support Python 3 yet
IT's obvious but I didn't think about that problem when open the ticket

**Comment by eglaubauf** [comment]
Sorry for the late reply. There is a branch for python3, which should work :) but it´s still under development. But my tests were fine so far.
