### ISSUE TITLE
Commercial houdini license downgrade to indie once egRedTools installed... no warning

### ISSUE THREAD

**Issue by gfxman** [eglaubauf/egRedshiftTools#4]
Hi,
i've lost my mind for 3 days on this. After installing this suite of open gl and redshift tools, my license was always downgraded to indie.
houdini does not tell you anything about this or why.... i've found out that agRedshiftTools, once installed, makes houdini open as Indie license.

I don't know if you can fix it or not, but at least a warning, could be usefull!

**Comment by eglaubauf** [comment]
Hey,

thanks for reaching out. I am no longer maintaining this toolset actively, but I added another line in the readme. With the only hdaLC assets provided your scenes always will be downgraded to Indie.
